# Generated by Django 3.2.5 on 2024-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pick', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('drop', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('number', models.IntegerField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
    ]
